import re

# Simplified SQL statement for testing
sql_statement = """
UPDATE GABM_CMPGN CMPNX

SET CMPGN_NM = IN_CMPGN_NM0
,CMPGN_DS = IN_CMPGN_DS
,CMPGN_PROMO_CD = IN_CMPGN_PROMO_CD
,CMPGN_STA_TX = IN_CMPGN_STA_TX
,LST_UPDT_TS = CURRENT_TIMESTAMP
,CMPGN_CONTEST_MAX_ENTER_CT = IN_CMPGN_CONTEST_MAX_ENTER_CT
,CMPGN_TRGT_REGIS_CT =IN_CMPGN_TRGT_REGIS_CT
,BUS_PRTR_DRCT_OWN_NM  =IN_BUS_PRTR_DRCT_OWN_NM
,CMPGN_STRT_DT = IN_CMPGN_STRT_DT
,CMPGN_END_DT = IN_CMPGN_END_DT
,DA_PRG_DT =IN_DA_PRG_DT

,UPDT_BY_USER_TYPE_TX = IN_UPDT_BY_USER_TYPE_TX
,ENROLL_SUC_EMAIL_SEND_IN =IN_ENROLL_SUC_EMAIL_SEND_IN
,ENROLL_SUC_EMAIL_TMPLT_ID =IN_ENROLL_SUC_EMAIL_TMPLT_ID
,ENROLL_STA_EMAIL_SEND_IN =IN_ENROLL_STA_EMAIL_SEND_IN
,ENROLL_STA_EMAIL_TMPLT_ID =IN_ENROLL_STA_EMAIL_TMPLT_ID

,CMPGN_IM_URL_AD_TX = IN_CMPGN_IM_URL_AD_TX
,EMS_EXTNL_PROMO_ID = IN_EMS_EXTNL_PROMO_ID
WHERE CMPGN_ID = IN_CMPGN_ID

"""
# Simplified SQL statement for testing
sql_statement1 = """
UPDATE GABM_APPL_CMPNT_RWRD_PARM ACRP
SET ACRP.ACT_IN ='N', ACRP.LST_UPDT_BY_PRCS_NM = IN_LST_UPDT_BY_PRCS_NM, ACRP.LST_UPDT_TS = CURRENT_TIMESTAMP
WHERE ACRP.RWRD_ID IN; (SELECT CR.RWRD_ID FROM GABM_CMPGN_RWRD CR WHERE CR.CMPGN_ID = IN_CMPGN_ID);
"""

# Updated regex pattern to test
db2_update_pattern = re.compile(r'UPDATE\s+(\w+)(?:\s+\w+)?\s+SET\s+([\s\S]+?)(?:\s+WHERE|\s*;)', re.IGNORECASE)

# Test the updated regex pattern
matches = db2_update_pattern.findall(sql_statement)
print("Matches for sql_statement:", matches)

matches1 = db2_update_pattern.findall(sql_statement1)
print("Matches for sql_statement1:", matches1)
